services:
  django:
    container_name: django
    build:
      context: .
    command: bash -c "uv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
